### ISSUE TITLE
Check columns

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#198]
Check all columns to see if they are correctly filled.
E.g. PM columns, isVar, computePri  etc.

Done various fixes. Still need to do more tests

**Comment by wfastrononomer** [comment]
Most of these are populated to some extent, although not the PM columns. 
Looking into the reasons behind this and and other issues. I will write a test script which will check expected values, number of sources etc.

**Comment by tms-epcc** [comment]
11/JUL/24
- needs more code to do the checks systematically

**Comment by tms-epcc** [comment]
14/AUG/24
- quite a broad ticket, may split this into a few tests

**Comment by tms-epcc** [comment]
see #632 for details

**Comment by tms-epcc** [comment]
29/APR/25
- this will be part of Harry's work in due course

**Comment by wfastrononomer** [comment]
Adding code in cu44 directory.

First checks on sourceID - issue with VVV - some gaps. Did we exclude one frameSet for some reason in VVVDR5. 
Check up on this. 

Traceback (most recent call last):
  File "./curation/invocations/cu44/AllSkySourceColumnChecks.py", line 280, in <module>
    tester.run()
  File "./curation/invocations/cu44/AllSkySourceColumnChecks.py", line 87, in run
    self.sourceIDCheck()
  File "./curation/invocations/cu44/AllSkySourceColumnChecks.py", line 118, in sourceIDCheck
    survInfo.minSourceID+survInfo.nSource-1))
ValueError: Maximum sourceID from survey VVV is incorrect: 515986796912, rather than 515986758473


Might be better to list problems in a file rather than raise ValueErrors each time.

**Comment by tms-epcc** [comment]
24/JUN/26
- uncovered issues with VVV and VHS but not clear if these are of major concern
    - for VVV DR5 - break in source ids- this will be replaced so less of a concern
    - for VHS DR7 - break in frameset ids - this will not be replaced so this could be a concern
- not sure if these breaks mean there is an issue in the processing
- added in more consistency checks 
- will add checks on same number of framesets as there are required unique field ids in required tiles, also examine where the missing source ids are and hence check the framesets. Also check the ordering.

**Comment by wfastrononomer** [comment]
VULCANiDR> select surveyName,COUNT(*) from allSkyNIRFrameSetInfo as f,allSkyNIRSource as s where f.frameSetID=s.frameSetID and s.zAllAperMagNoAperCorr3>0. and s.yAllAperMagNoAperCorr3>0. and ABS((zAllAperMagNoAperCorr3-yAllAperMagNoAperCorr3)-zmyallext)>0.00001 group by surveyName
.-------------------------------
.| | surveyName |            | |
.-------------------------------
.|>| VVV        | 296865756  |<|
.-------------------------------

It seems that VVV is getting incorrect extended source colours or magnitudes without aperture correction.
Probably this is because these columns are not in VVV and are put into ASNIR for consistency. A mistake must have been made in the code.

**Comment by wfastrononomer** [comment]
Added simple stats checks for passband columns, r14153.

**Comment by wfastrononomer** [comment]
24/8/2026. Analysing output and checking. Some of the output for extended source colours vs point source colours seems incorrect:

e.g. "DXS should have different colours for ymjallpnt and ymjtelpnt, but doesn't" There is no Y band in DXS, so all should be default. I think I have already fixed this issue - it no longer selects defaults. 

Delete those messages as they are no longer relevant.

**Comment by wfastrononomer** [comment]
"There are 326337095 incorrect ymjallext colours in survey VVV (colours don't match magnitudes)" This is still true in VULCANiDR, but the code has been corrected, see #1007. Delete these ones.

**Comment by wfastrononomer** [comment]
"There are 25653239 incorrect jmkallext colours in survey GCS (colours don't match magnitudes)" - also LAS, GPS, UHS

Checked recent run on small area, no problematic colours. Delete these ones.

**Comment by wfastrononomer** [comment]
"DXS should have different colours for zmytelpnt and zmyallpnt, but doesn't" - same as above message with columns switched around. Reran on small test DB and these messages don't appear. Will delete.

There are 296865756 incorrect zmytelext colours in survey VVV (colours don't match magnitudes), see above, fixed in #1007

**Comment by wfastrononomer** [comment]
"Survey VIKING has 119330 default measurements for zmjd"
select COUNT(*) from allSkyNIRSource as s,allSkyNIRFrameSetInfo as f where f.frameSetID=s.frameSetID and f.surveyName='VIKING'
.------------------
.| |            | |
.------------------
.|>| 94819861   |<|
.------------------
Rows returned: 1 (execution time: 17.3625 s)
VULCANiDR> select COUNT(*) from allSkyNIRSource as s,allSkyNIRFrameSetInfo as f where f.frameSetID=s.frameSetID and f.surveyName='VIKING' and f.zmfID>0
.------------------
.| |            | |
.------------------
.|>| 93721546   |<|
.------------------
~0.1% of all sources with Z-band observations are default? Put better messaging in? About 0.18% of ones with zTelAperMag3>0. I suspect these are ones where grouting has thrown a weird result and no value for mid in detection table. Only VISTA surveys seem to be affected for mjd. Add in the proportion of defaults and check a few results in the original releases. 

Check original releases and FITS data. Basically it is tiles where MJDoff column = 0. These do not have sensible values, and are an artifact of the tiling process. 

Updated code in r14161. Should only put lines in if >0.3% defaults.

**Comment by wfastrononomer** [comment]
Survey VIDEO has 11720 default measurements for zhlcorsmjradas
Survey VIKING has 60233 default measurements for zhlcorsmjradas

Again small numbers, see above, r14161 fix, should remove these if it is just the odd ones. Perhaps check which ones.

**Comment by wfastrononomer** [comment]
"There isn't data for zhlcorsmjradas from both telescopes so a comparison between the telescopes is not possible"

Correct. Hope to sort out before VULCANDR1

**Comment by wfastrononomer** [comment]
"GCS zxi has 33331676 values, but no variation in values: 0.0+/-0.0
VIDEO zxi has 1742880 values, but no variation in values: 0.0+/-0.0
VIKING zxi has 68548689 values, but no variation in values: 0.0+/-0.0
VVV zxi has 317587905 values, but no variation in values: 0.0+/-0.0
No variation in values of zxi across telescopes
GCS zeta has 33331676 values, but no variation in values: 0.0+/-0.0
VIDEO zeta has 1742880 values, but no variation in values: 0.0+/-0.0
VIKING zeta has 68548689 values, but no variation in values: 0.0+/-0.0
VVV zeta has 317587905 values, but no variation in values: 0.0+/-0.0
No variation in values of zeta across telescopes"

I think this is just that xi and eta are calculated relative to the bluest filters, except in VMC, where it is done in reverse order K,J,Y.

Perhaps do a separate xi, eta set of tests.

**Comment by wfastrononomer** [comment]
"Survey GCS has a hmjd mean value = 54363.3841604, which is significantly differ\
ent from the UKIRT mean of 56379.2893854+/-575.62962659
Survey UHS has a hmjd mean value = 59520.4533617, which is significantly differ\
ent from the UKIRT mean of 56379.2893854+/-575.62962659"

I think this is just reflective of observation strategy and prioritisation, but might be worth a quick Look.

**Comment by wfastrononomer** [comment]
Have other comparisons worked - between WFCAM and VISTA. Also more sophisticated measurements...

**Comment by tms-epcc** [comment]
03/SEP/26
- @wfastrononomer - is this needed for the IDR?

**Comment by wfastrononomer** [comment]
Added checks for defaults.
I think this is completed for now.
