### ISSUE TITLE
PawprintAverages issue

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#637]
Traceback (most recent call last):
  File "/unas/scos/usr/local/lib/python2.7/multiprocessing/process.py", line 267
, in _bootstrap
    self.run()
  File "/unas/scos/usr/local/lib/python2.7/multiprocessing/process.py", line 114
, in run
    self._target(*self._args, **self._kwargs)
  File "/unas/njc/VDFS/ListDrivenClean/src/curation/invocations/cu9/PawprintValu
esAverager.py", line 1265, in processFrame
    allWeights, weights, allExt17 = self.getOffSets(offsetSelData, weights, fram
eSet)
  File "/unas/njc/VDFS/ListDrivenClean/src/curation/invocations/cu9/PawprintValuesAverager.py", line 1121, in getOffSets
    raise ValueError("No catalogue in frameSet has multiframeID=%d" % mfID)
ValueError: No catalogue in frameSet has multiframeID=4950135
# 2024-10-25 11:50:07.41: <ERROR> Thread failed. Terminating all other running threads.

multiframeID=4950135 is catalogueID=4929

Fails on combiCatID=7571.

**Comment by wfastrononomer** [comment]
SELECT v.combicatID,r.apertureID,r.multiframeID,r.extNum,avera
geConf,ppErrBits,isoMag,isoLup,isoJky,aperJkyNoAperCorr1,aperJky1,aperJky1err,ap
erJkyNoAperCorr2,aperJky2,aperJky2err,aperJkyNoAperCorr3,aperJky3,aperJky3err,ap
erJkyNoAperCorr4,aperJky4,aperJky4err,aperJkyNoAperCorr5,aperJky5,aperJky5err,ap
erJkyNoAperCorr6,aperJky6,aperJky6err,aperJkyNoAperCorr7,aperJky7,aperJky7err,ap
erJky8,aperJky8err,aperJky9,aperJky9err,aperJky10,aperJky10err,aperJky11,aperJky11err,aperJky12,aperJky12err,aperJky13,aperJky13err FROM MapProvenance as v,MapFrameStatus as mfs,ultravistaMapRemeasurementPhotometry as r,ultravistaMapRemeasurementRaw as a WHERE v.catalogueID=mfs.catalogueID and mfs.catalogueID=r.catalogueID and mfs.mapID=2 and averageConf>0. and avSetupID=1 and a.deprecated=0 and r.catalogueID in (6616,6406,6448,6484,6240,6350,6361,6323,6284,6107,6035,5864,5667,5557,5582,5576,5798,6961,6837,6814,7093,7089,7001,921,2319,3025,3016,2841,3645,4334,4331,4307,5462,5422,5504,5211,5140,5159,5175,5169,5107,4789,4765,4766,4754,4913,4946,4540,4505,4460,4646,4564) and r.apertureID=a.apertureID and r.catalogueID=a.catalogueID OPTION (MAXDOP 1)

**Comment by wfastrononomer** [comment]
Why the catalogueID selection above?

**Comment by wfastrononomer** [comment]
select * from MapProvenance where catalogueID=4929
---------------------------------------------------------------------------
| | combicatID          | catalogueID         | avSetupID  | cuEventID  | |
---------------------------------------------------------------------------
|>| 7549                | 4929                | 1          | 78501      |<|
|>| 7776                | 4929                | 2          | 78501      |<|
--------------------------------------------------------------------------

**Comment by wfastrononomer** [comment]
elect combiCatID,min(mjdObs),max(mjdObs) from MapProvenance as mp,MapFrameStatus as mfs,Multiframe as m where mp.avSetupID=1 and mp.catalogueID=mfs.catalogueID and mfs.multiframeID=m.multiframeID and combiCatID in (7549,7571) group by combiCatID
-----------------------------------------------------------
| | combiCatID          |               |               | |
-----------------------------------------------------------
|>| 7549                | 57009.3       | 57146.1       |<|
|>| 7571                | 59222.2       | 59297.1       |<|
-----------------------------------------------------------

**Comment by wfastrononomer** [comment]
Why is multiframeID in ultravistaMapRemeasurementRaw different from MapFrameStatus for the same catalogueID?

select COUNT(*) from MapFrameStatus as mfs, ultravistaMapRemeasurementRaw as r where mfs.programmeID=160 and mfs.mapID=2 and mfs.catalogueID=r.catalogueID and mfs.multiframeID!=r.multiframeID
------------------
| |            | |
------------------
|>| 48247111   |<|
------------------

 select COUNT(distinct mfs.catalogueID) from MapFrameStatus as mfs, ultravistaMapRemeasurementRaw as r where mfs.programmeID=160 and mfs.mapID=2 and mfs.catalogueID=r.catalogueID and mfs.multiframeID!=r.multiframeID
------------------
| |            | |
------------------
|>| 223        |<|
------------------

Why?

...
 390                 | 5721230             | 4934136             |<|
|>| 2765                | 6747151             | 4395318             |<|
|>| 539                 | 6266447             | 5898942             |<|
|>| 3183                | 4942671             | 5010725             |<|
|>| 2597                | 4341605             | 4335032             |<|
|>| 3525                | 6661995             | 4934288             |<|
|>| 2470                | 6048839             | 5767897             |<|
|>| 1536                | 4443142             | 5021046             |<|
|>| 1785                | 4698962             | 4853098             |<|
|>| 1051                | 6332176             | 4844653             |<|
|>| 2370                | 4942995             | 5010076             |<|
|>| 3272                | 6605915             | 4337513             |<|
|>| 3793                | 5013494             | 5776144             |<|
|>| 2375                | 6373454             | 4319471             |<|
|>| 1482                | 5454180             | 4868228             |<|
|>| 310                 | 4427794             | 5011242             |<|
|>| 2852                | 4923089             | 5016898             |<|
|>| 1973                | 6700601             | 5077466             |<|
|>| 35                  | 6397429             | 5013345             |<|
|>| 246                 | 4938642             | 4924731             |<|
|>| 3345                | 6237962             | 5899293             |<|
-----------------------------------------------------------------------

**Comment by wfastrononomer** [comment]
catalogue names in MapFrameStatus are a better match to multiframeId from MapFrameStatus [Does this prove anything?]
Best check the numbers in MapRemeasurementRaw and figure out what is going on..

**Comment by wfastrononomer** [comment]
select COUNT(*) from ultravistaMapRemeasurementRaw where catalogueID=1785 and extNum=2
------------------
| |            | |
------------------
|>| 12623      |<|
------------------

but /disk62/sys/test/products/map/20240719_v6/v20180428_00223_st_map160_2_1.fits extNum=2:

BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                  336 / length of dimension 1
NAXIS2  =                12386 / length of dimension 2
PCOUNT  =                    0 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                   81 / number of table fields

**Comment by wfastrononomer** [comment]
Try to work out how the catalogues got messed up.

1785                | 4698962             | 4853098             | /disk62/sys/test/products/map/20240719_v6/v20180428_00223_st_map160_2_1.fits | /disk65/vsa/ingest/fits/20140316_v1.5/v20140316_00311_st_cat.fits |<|

**Comment by wfastrononomer** [comment]
cuEventIds 14431 and 14441 are where it happened

**Comment by wfastrononomer** [comment]
Problem was GIGO - garbage earlier in pipeline.
Add checks for this.

**Comment by wfastrononomer** [comment]
Fixed
